# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/Chick/Vivado Builds/FPGAPCIE/FPGAPCIE.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_9/bd_d92b_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d92b_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Chick/Vivado Builds/FPGAPCIE/FPGAPCIE.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_9/bd_d92b_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d92b_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
